---
title: "R for Data Science"
output: 
  html_notebook: 
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---

1. Notes and exercises from [R for Data Science book from Grolemund and Wickham]( http://r4ds.had.co.nz/)
1. [Slack](https://rfordatascience.slack.com/)

# [Curriculum](https://docs.google.com/document/d/1HWpqJJLEHoZW-edJuDH0WWxZbKltZG95Wx6uwXPK0so/edit)



| Week | Theme         | Sections       |
|------|---------------|----------------|
| 1    | Explore       | 1, 4, 6, 8     |
| 2    |               | 2, 3           |
| 3    |               | 5              |
| 4    |               | 7              |
| 5    | Wrangle       | 9, 10,11       |
| 6    |               | 12, 13         |
| 7    |               | 14             |
| 8    |               | 15, 16         |
| 9    | Program       | 17, 18, 19     |
| 10   |               | 20, 21         |
| 11   | Model         | 22, 23, 24, 25 |
| 12   |               |                |
| 13   | Communication | 27, 28, 29, 30 |
| 14   | Proyects      |                |

# Explore

```{r packages, eval=FALSE}
library(tidyverse)
```

```{r dataset registrations}
registrations <- read_csv("./datasets/registrations.csv")
```
```{r glimpse of registrations}
glimpse(registrations)
```
```{r summary of registrations}
summary(registrations)
```
```{r explore registrations}
registrations %>% 
        filter(`Are you signing up as a learner or as a mentor?` == "Learner") %>%
        ggplot(aes(x = `How comfortable are you with data analysis and/or statistics?`)) + 
        geom_bar() + 
        labs(title = "Learners")


```

```{r mentors}
registrations %>% 
        filter(`Are you signing up as a learner or as a mentor?` == "Mentor") %>%
        ggplot(aes(x = `How comfortable are you with data analysis and/or statistics?`)) + 
        geom_bar() + 
        labs(title = "Mentors")
```


```{r geocoded }
library(forcats)
library(magrittr)
library(scales)
library(ggmap) 
locations <-  registrations %>%
        select(`Where will you be joining us from? (City, State/Province, Country)`) %>%
        separate(`Where will you be joining us from? (City, State/Province, Country)`,
           into = c("first", "second"),
           sep = " and ",                               
           remove = FALSE) %>% 
        select(location = first) %>% # some people entered e.g. "UK and Switzerland", will take the first one
        mutate(location = ifelse(location == "" | is.na(location), "Missing", location))

geocoded <-  geocode(locations$location, output = "more", source = 'dsk')
```

```{r}
geocoded %>% 
        select(country) %>% 
        
```


# Wrangle

# Program

# Model

# Communication